'use client';
import {useEffect,useRef,useState} from 'react';
import {flushSync} from 'react-dom';
import {ArrowUpRight,RotateCcw,Move3D,Layers3,MousePointer2,ChevronRight,Box,Scan,CarFront,Armchair,Lightbulb,CircleDot,Maximize,Plus,Minus,Orbit,Grid2X2,Info,X,Focus,BookOpen} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Tooltip,TooltipProvider,TooltipTrigger,TooltipContent} from '@/components/ui/tooltip';
import VehicleScene,{type SceneHandle} from './vehicle-scene';
import parts from './parts.json';
const systems=[
 {id:'all',zh:'全部部件',en:'All components',icon:Layers3,detailZh:'从整体到细节，探索车辆的构成。',detailEn:'Explore the complete car, one piece at a time.'},
 {id:'body',zh:'车身与外观',en:'Body & exterior',icon:CarFront,detailZh:'车身面板、外饰与支撑构件，勾勒 Model Y 的流线轮廓。',detailEn:'Body panels, exterior trim and supporting elements shape the Model Y silhouette.'},
 {id:'glass',zh:'玻璃与车窗',en:'Glass & windows',icon:Scan,detailZh:'全景玻璃车顶与车窗，连接座舱和外部视野。',detailEn:'Panoramic roof glazing and windows connect the cabin to the world outside.'},
 {id:'cabin',zh:'座舱与内饰',en:'Cabin & interior',icon:Armchair,detailZh:'探索座舱中的内饰表面、座椅与仪表区域。',detailEn:'Explore interior surfaces, seating and the dashboard area.'},
 {id:'lights',zh:'灯组与照明',en:'Lights & optics',icon:Lightbulb,detailZh:'查看前后灯组的透镜、反光结构和灯罩。',detailEn:'Inspect the lenses, reflectors and covers within the lighting assemblies.'},
 {id:'wheels',zh:'车轮与制动',en:'Wheels & brakes',icon:CircleDot,detailZh:'从轮胎、轮辋到制动盘与卡钳，观察车轮的层次结构。',detailEn:'Look inside the wheel assemblies: tires, rims, brake discs and calipers.'},
];
type Language='zh'|'en';
type Registry={registerTool:(tool:{name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>void|Promise<void>};
export default function Home(){
 const [language,setLanguage]=useState<Language>('zh'),[explosion,setExplosion]=useState(0),[category,setCategory]=useState('all'),[selected,setSelected]=useState(''),[isolate,setIsolate]=useState(false),[rotate,setRotate]=useState(false),[wireframe,setWireframe]=useState(false),[ready,setReady]=useState(false),[directory,setDirectory]=useState(false),[about,setAbout]=useState(false),[view,setView]=useState('perspective');
 const scene=useRef<SceneHandle>(null);const current=useRef({explosion,category,selected,isolate,language,ready});current.current={explosion,category,selected,isolate,language,ready};
 const zh=language==='zh',t=(cn:string,en:string)=>zh?cn:en;
 const active=systems.find(s=>s.id===category)!,piece=parts.find(p=>p.id===selected),filtered=parts.filter(p=>category==='all'||p.category===category);
 useEffect(()=>{document.documentElement.lang=language==='zh'?'zh-CN':'en'},[language]);
 function choose(id:string){setSelected(id);if(id){const p=parts.find(v=>v.id===id);if(p)setCategory(p.category)}else setIsolate(false)}
 function reset(){setExplosion(0);setCategory('all');setSelected('');setIsolate(false);setRotate(false);setWireframe(false);setView('perspective');scene.current?.fit()}
 useEffect(()=>{
  const context=(document as Document&{modelContext?:Registry}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
  const register=(tool:Parameters<Registry['registerTool']>[0])=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}};
  register({name:'get_tesla_exploration',description:'Read current Model Y exploration state and selectable component IDs.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({...current.current,parts:parts.map(p=>({id:p.id,category:p.category,name:p.en}))})});
  register({name:'set_tesla_exploration',description:'Update the visible Model Y explosion, category, selected part and isolated view.',inputSchema:{type:'object',properties:{explosion:{type:'number',minimum:0,maximum:100},category:{type:'string',enum:systems.map(s=>s.id)},selected:{type:'string'},isolate:{type:'boolean'}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input)=>{
   if(!input||typeof input!=='object'||Array.isArray(input))throw Error('Expected an object');const v=input as Record<string,unknown>;
   if(Object.keys(v).some(k=>!['explosion','category','selected','isolate'].includes(k)))throw Error('Unknown field');
   if(v.explosion!==undefined&&(typeof v.explosion!=='number'||!Number.isFinite(v.explosion)||v.explosion<0||v.explosion>100))throw Error('Explosion must be between 0 and 100');
   if(v.category!==undefined&&!systems.some(s=>s.id===v.category))throw Error('Unknown category');
   if(v.selected!==undefined&&(typeof v.selected!=='string'||(v.selected!==''&&!parts.some(p=>p.id===v.selected))))throw Error('Unknown part ID');
   if(v.isolate!==undefined&&typeof v.isolate!=='boolean')throw Error('isolate must be boolean');
   if(!current.current.ready)throw Error('Model is still loading');
   flushSync(()=>{if(v.explosion!==undefined)setExplosion(v.explosion as number);if(v.category!==undefined)setCategory(v.category as string);if(v.selected!==undefined)choose(v.selected as string);if(v.isolate!==undefined)setIsolate(v.isolate as boolean)});
   return current.current;
  }});
  return()=>lifecycle.abort();
 },[]);
 function Tool({label,active=false,action,children}:{label:string;active?:boolean;action:()=>void;children:React.ReactNode}){return <Tooltip><TooltipTrigger className={'tool-button '+(active?'active':'')} aria-label={label} onClick={action}>{children}</TooltipTrigger><TooltipContent>{label}</TooltipContent></Tooltip>}
 return <TooltipProvider delay={200}><main className="studio">
 <header className="topbar"><a href="/" className="brand" aria-label="Tina 3D Tesla"><img src="/brand/tina-wordmark.svg" className="brand-wordmark" width="174" height="36" alt="TINA"/><span className="brand-descriptor">3D Tesla</span></a><div className="top-caption">{t('独立汽车设计探索','Independent automotive exploration')}</div><div className="header-actions"><button className="about-button" onClick={()=>setAbout(true)} aria-label={t('关于模型','About the model')}><Info size={17}/></button><button className="language" onClick={()=>setLanguage(zh?'en':'zh')} aria-label={zh?'Switch to English':'切换为中文'}><span className={zh?'chosen':''}>中</span><i>/</i><span className={!zh?'chosen':''}>EN</span></button></div></header>
 <section className="workspace"><div className={'stage '+(explosion>45||isolate?'expanded':'')}>
 <div className="vehicle-heading"><span className="eyebrow">{t('特斯拉 / Tesla','Tesla / 特斯拉')}</span><h1>Model Y<span>2021</span></h1><p>{t('每个细节，皆有意义。','Every piece has a purpose.')}<br/><span>{t('A closer look at what moves us.','以全新视角，探索每一个细节。')}</span></p></div>
 <div className="stage-mark" aria-hidden="true">Y</div><VehicleScene ref={scene} explosion={explosion} category={category} selected={selected} isolate={isolate} rotate={rotate} wireframe={wireframe} language={language} onSelect={choose} onReady={setReady}/>
 <div className="stage-tag"><span className="live-dot"/>{t('交互式 3D 模型','Interactive 3D model')}</div>
 <div className="view-controls" role="group" aria-label={t('观察角度','Camera views')}>{[['perspective','透视','Perspective'],['front','正面','Front'],['side','侧面','Side'],['top','俯视','Top']].map(([id,cn,en])=><button key={id} disabled={!ready} className={view===id?'active':''} onClick={()=>{setView(id);scene.current?.view(id as 'front'|'side'|'top'|'perspective')}}>{t(cn,en)}</button>)}</div>
 <div className="stage-tools"><Tool label={t('适应视图','Fit model')} action={()=>{scene.current?.fit();setView('perspective')}}><Maximize size={17}/></Tool><Tool label={t('放大','Zoom in')} action={()=>scene.current?.zoom(.8)}><Plus size={18}/></Tool><Tool label={t('缩小','Zoom out')} action={()=>scene.current?.zoom(1.25)}><Minus size={18}/></Tool><span className="tool-rule"/><Tool label={t('自动旋转','Auto rotate')} active={rotate} action={()=>setRotate(!rotate)}><Orbit size={18}/></Tool><Tool label={t('线框模式','Wireframe')} active={wireframe} action={()=>setWireframe(!wireframe)}><Grid2X2 size={16}/></Tool></div>
 {selected&&piece&&<div className="selection-chip"><span className="live-dot"/><span>{piece.id} <b>{zh?piece.zh:piece.en}</b></span><button aria-label={t('清除选择','Clear selection')} onClick={()=>choose('')}><X size={14}/></button></div>}
 <div className="stage-bottom"><div className="parts-stat"><b>{parts.length}</b><div>{t('可探索部件','Explorable pieces')}<span>{t('独立网格 · 非原厂零件编号','Mesh pieces · Not OEM part IDs')}</span></div></div><div className="stage-instruction"><MousePointer2 size={15}/><span>{t('拖动旋转 · 滚轮缩放','Drag to orbit · Scroll to zoom')}<br/>{t('点击部件，深入探索','Click a piece to explore')}</span></div></div>
 </div>
 <aside className="inspector" aria-label={t('模型控制面板','Model controls')}><div className="panel-title"><span>{t('探索车辆','Explore the vehicle')}</span><span className="small">{t('Explore','探索')}</span></div><div className="model-label"><div className="tiny-car"><CarFront size={29} strokeWidth={1.25}/></div><div><b>Tesla Model Y</b><p>{t('2021 款 · 纯电跨界车','2021 · Electric crossover')}</p></div><ArrowUpRight size={17}/></div>
 <div className="section-label">{t('查看方式','View mode')}<span>{t('View mode','查看方式')}</span></div><div className="mode-switch"><button aria-pressed={explosion===0} className={explosion===0?'active':''} onClick={()=>{setExplosion(0);setIsolate(false);setView('perspective')}}><CarFront size={14}/>{t('整车','Assembled')}</button><button aria-pressed={explosion>0} className={explosion>0?'active':''} onClick={()=>{setExplosion(65);setIsolate(false);setView('perspective')}}><Box size={14}/>{t('拆解','Exploded')}</button></div>
 <div className="slider-label"><span>{t('拆解程度','Explosion level')}</span><b>{Math.round(explosion)}<small>%</small></b></div><Slider aria-label={t('拆解程度，0 为完整，100 为完全展开','Explosion level: 0 assembled, 100 fully separated')} value={[explosion]} min={0} max={100} step={1} onValueChange={v=>{setExplosion(Array.isArray(v)?v[0]:v);setIsolate(false);setView('perspective')}}/><div className="range-labels"><button onClick={()=>{setExplosion(0);setIsolate(false)}}>{t('完整','Assembled')}</button><button onClick={()=>{setExplosion(100);setIsolate(false)}}>{t('完全展开','All pieces')}</button></div>
 <div className="section-label">{t('部件系统','Component systems')}<span>{t('Components','部件系统')}</span></div><div className="systems">{systems.map(s=><button key={s.id} aria-pressed={category===s.id} className={'system-row '+(category===s.id?'selected':'')} onClick={()=>{setCategory(s.id);setSelected('');setIsolate(false)}}><s.icon size={18} strokeWidth={1.5}/><span>{zh?s.zh:s.en}</span><small>{s.id==='all'?parts.length:parts.filter(p=>p.category===s.id).length}</small><ChevronRight size={13}/></button>)}</div>
 <div className="isolate-row"><label htmlFor="isolate">{t(selected?'仅显示当前部件':'仅显示当前系统',selected?'Isolate selected piece':'Isolate selected system')}</label><Switch id="isolate" checked={isolate} onCheckedChange={setIsolate}/></div>
 <div className={`part-detail ${category==='all'&&!piece?'idle':''}`} aria-live="polite"><div className="detail-top"><span>{selected?selected:t('细节观察','A closer look')}</span>{piece&&<button onClick={()=>choose('')} aria-label={t('清除选择','Clear selection')}><X size={14}/></button>}</div><b>{piece?(zh?piece.zh:piece.en):(zh?active.zh:active.en)}</b><p>{zh?active.detailZh:active.detailEn}</p>{piece&&<small>{t('模型材质','Model material')}: {piece.material} · {t('可视网格','Visual mesh')}</small>}</div>
 <button className="directory-button" onClick={()=>setDirectory(true)}><BookOpen size={16}/>{t('打开部件目录','Open component directory')}<span>{filtered.length}</span><ArrowUpRight size={14}/></button><button className="reset-button" onClick={reset}><RotateCcw size={14}/>{t('重置全部视图','Reset everything')}</button>
 </aside></section>
 <footer><span className="footer-brand"><img src="/brand/tina-wordmark.svg" className="footer-wordmark" width="174" height="36" alt="TINA"/><span>3D Tesla</span></span><span>{t('Tina AI 独立设计探索，非特斯拉官方产品。','Tina AI independent design exploration. Not affiliated with Tesla.')}</span><button onClick={()=>setAbout(true)}>{t('模型来源与说明','Model credits & scope')}<ArrowUpRight size={12}/></button></footer>
 <Sheet open={directory} onOpenChange={setDirectory}><SheetContent className="directory-sheet"><SheetHeader><SheetTitle>{t('部件目录','Component directory')} <small>{filtered.length}</small></SheetTitle><SheetDescription>{t('选择任一部件并单独观察。编号为本站网格编号。','Select any piece to inspect it. IDs identify meshes in this study.')}</SheetDescription></SheetHeader><div className="directory-filters">{systems.map(s=><button key={s.id} className={category===s.id?'active':''} onClick={()=>setCategory(s.id)}>{zh?s.zh:s.en}</button>)}</div><div className="part-list">{filtered.map(p=><button key={p.id} className={selected===p.id?'active':''} onClick={()=>{choose(p.id);setIsolate(true);setRotate(false);setDirectory(false)}}><span>{p.id}</span><b>{zh?p.zh:p.en}</b><Focus size={15}/></button>)}</div></SheetContent></Sheet>
 <Sheet open={about} onOpenChange={setAbout}><SheetContent className="about-sheet"><SheetHeader><SheetTitle>{t('关于这个模型','About this model')}</SheetTitle><SheetDescription>Tina 3D Tesla · Model Y 2021</SheetDescription></SheetHeader><div className="about-copy"><Move3D size={38} strokeWidth={1}/><h2>{t('换一个角度，理解设计。','See the design from within.')}</h2><p>{t('本站采用 2021 款 Tesla Model Y 的艺术家模型，将网格按连接关系分离为 397 个可交互部件，并优化几何与材质以适应浏览器展示。','This study uses an artist-created 2021 Tesla Model Y model, separated into 397 interactive mesh pieces by geometry connectivity, with optimized geometry and studio materials.')}</p><p>{t('这些是可视网格，不等同于特斯拉维修零件。模型并非完整工程 CAD，不包含经验证的电池、电驱或底盘内部零件目录。','These are visual mesh pieces, not Tesla service parts. This is not complete engineering CAD and does not include a verified battery, drivetrain or internal chassis parts catalog.')}</p><h3>{t('模型与授权','Model & license')}</h3><p><a href="https://sketchfab.com/3d-models/tesla-model-y-2021-c0a86cac582d4b33aba0fb1b1912d970" target="_blank" rel="noreferrer">Tesla Model Y 2021</a> {t('作者','by')} <a href="https://sketchfab.com/763468712" target="_blank" rel="noreferrer">763468712</a>.<br/><a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">Creative Commons Attribution 4.0</a>.<br/>{t('已进行网格拆分、面数优化、尺寸归一化和材质调整。','Adapted through mesh separation, polygon reduction, scale normalization and material changes.')}</p><p><a href="/models/LICENSE.txt" target="_blank" rel="noreferrer">{t('完整模型署名','Full model attribution')}</a></p><h3>{t('交互参考','Interaction reference')}</h3><p><a href="https://github.com/ashemag/model-x-studio" target="_blank" rel="noreferrer">ashemag / model-x-studio</a><br/>{t('参考其渐进拆解与独立部件观察的交互思路。本站车辆为 Model Y。','Inspired by its progressive explosion and individual-piece inspection. This site depicts Model Y.')}</p></div></SheetContent></Sheet>
 </main></TooltipProvider>;
}
